# 正式环境
server:
  #医院服务器端口
  #port: 8089
  #公司测试服务器端口
  port: 8084
  servlet:
    session:
      timeout: PT10H
      # Duration转换字符串方式，默认为正，负以-开头，
      # 紧接着P，（字母不区分大小写）D ：天 T：天和小时之间的分隔符 H ：小时 M：分钟 S：秒
      # 每个单位都必须是数字，且时分秒顺序不能乱。例：PT2H就是2个小时，7200秒。

# mybaits 模块配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.annet.entity


  #数据库输出结果集显示
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# sql打印
logging:
  level:
    com.annet.mapper: DEBUG



#web service
webservice:
  # 深圳公司本部（局域网）测试的webservice接口地址
  #Url: http://192.168.0.236:8081/BespokeWebService.asmx?wsdl
  #外网测试的webservice接口地址
  #Url: http://183.62.231.156:8089/BespokeWebService.asmx?wsdl
  #本地测试的webservice接口地址
  Url: http://127.0.0.1/BespokeWebService.asmx?wsdl
  #现场医院的webservice接口地址
  #Url: http://192.168.10.74:9091/BespokeWebService.asmx?wsdl
#数据库连接
spring:
  datasource:
    #公司总部测试库
    #url: jdbc:sqlserver://192.168.0.236:1433;DatabaseName=bespoke_hns
    #本地数据库
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=bespoke_cd_cs
    #url: jdbc:sqlserver://localhost:1433;DatabaseName=bespoke
    #url: jdbc:sqlserver://localhost:1433;DatabaseName=bespoke
    #医院现场测试数据库
    #url: jdbc:sqlserver://192.168.10.74:1433;DatabaseName=bespoke_cs
    #医院现场正式数据库
    #url: jdbc:sqlserver://192.168.10.74:1433;DatabaseName=bespoke
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123456
    #password: annet
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-While-Idle: true
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j,config

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    time-zoom: GMT+8

  #logback输出日志配置
  logging:
    config: classpath:logback-spring.xml

#是否是手机flage=0是电脑，flage=1是微信
#isTrue=0,已预约申请单可继续提交，isTrue=1,已预约申请单不可重复提交
family:
  flage: 1
  isTrue: 1
